package dendy.rpms.entity;

// Generated 2014-10-26 13:48:43 by Hibernate Tools 3.6.0

import javax.persistence.*;
import java.util.Date;

/**
 * AnimalGenotype generated by hbm2java
 */
@Entity
@Table(name = "animal_genotype", catalog = "rpms")
public class AnimalGenotype implements java.io.Serializable {

    private AnimalGenotypeId id;
    private Animal animal;
    private Primer primer;
    private Genotype genotypeByGenotypeB;
    private Genotype genotypeByGenotypeA;
    private Date createTime;

    public AnimalGenotype() {
    }

    public AnimalGenotype(AnimalGenotypeId id, Animal animal, Primer primer, Genotype genotypeByGenotypeB, Genotype genotypeByGenotypeA) {
        this.id = id;
        this.animal = animal;
        this.primer = primer;
        this.genotypeByGenotypeB = genotypeByGenotypeB;
        this.genotypeByGenotypeA = genotypeByGenotypeA;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "animal", column = @Column(name = "ANIMAL", nullable = false)),
            @AttributeOverride(name = "genotypeA", column = @Column(name = "GENOTYPE_A", nullable = false)),
            @AttributeOverride(name = "genotypeB", column = @Column(name = "GENOTYPE_B", nullable = false)),
            @AttributeOverride(name = "primer", column = @Column(name = "PRIMER", nullable = false))})
    public AnimalGenotypeId getId() {
        return this.id;
    }

    public void setId(AnimalGenotypeId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ANIMAL", nullable = false, insertable = false, updatable = false)
    public Animal getAnimal() {
        return this.animal;
    }

    public void setAnimal(Animal animal) {
        this.animal = animal;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRIMER", nullable = false, insertable = false, updatable = false)
    public Primer getPrimer() {
        return this.primer;
    }

    public void setPrimer(Primer primer) {
        this.primer = primer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GENOTYPE_B", nullable = false, insertable = false, updatable = false)
    public Genotype getGenotypeByGenotypeB() {
        return this.genotypeByGenotypeB;
    }

    public void setGenotypeByGenotypeB(Genotype genotypeByGenotypeB) {
        this.genotypeByGenotypeB = genotypeByGenotypeB;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GENOTYPE_A", nullable = false, insertable = false, updatable = false)
    public Genotype getGenotypeByGenotypeA() {
        return this.genotypeByGenotypeA;
    }

    public void setGenotypeByGenotypeA(Genotype genotypeByGenotypeA) {
        this.genotypeByGenotypeA = genotypeByGenotypeA;
    }

    @Column(name = "CREATE_TIME")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AnimalGenotype that = (AnimalGenotype) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
