package dendy.rpms.entity;

// Generated 2014-10-26 13:48:43 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnimalGenotypeId generated by hbm2java
 */
@Embeddable
public class AnimalGenotypeId implements java.io.Serializable {

	private long	animal;
	private long	genotypeA;
	private long	genotypeB;
	private long	primer;

	public AnimalGenotypeId() {
	}

	public AnimalGenotypeId(long animal, long genotypeA, long genotypeB, long primer) {
		this.animal = animal;
		this.genotypeA = genotypeA;
		this.genotypeB = genotypeB;
		this.primer = primer;
	}

	@Column(name = "ANIMAL", nullable = false)
	public long getAnimal() {
		return this.animal;
	}

	public void setAnimal(long animal) {
		this.animal = animal;
	}

	@Column(name = "GENOTYPE_A", nullable = false)
	public long getGenotypeA() {
		return this.genotypeA;
	}

	public void setGenotypeA(long genotypeA) {
		this.genotypeA = genotypeA;
	}

	@Column(name = "GENOTYPE_B", nullable = false)
	public long getGenotypeB() {
		return this.genotypeB;
	}

	public void setGenotypeB(long genotypeB) {
		this.genotypeB = genotypeB;
	}

	@Column(name = "PRIMER", nullable = false)
	public long getPrimer() {
		return this.primer;
	}

	public void setPrimer(long primer) {
		this.primer = primer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnimalGenotypeId))
			return false;
		AnimalGenotypeId castOther = (AnimalGenotypeId) other;

		return (this.getAnimal() == castOther.getAnimal()) && (this.getGenotypeA() == castOther.getGenotypeA())
				&& (this.getGenotypeB() == castOther.getGenotypeB()) && (this.getPrimer() == castOther.getPrimer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnimal();
		result = 37 * result + (int) this.getGenotypeA();
		result = 37 * result + (int) this.getGenotypeB();
		result = 37 * result + (int) this.getPrimer();
		return result;
	}

}
