package dendy.rpms.entity;

// Generated 2014-10-26 13:48:43 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeedType generated by hbm2java
 */
@Entity
@Table(name = "feed_type", catalog = "rpms")
public class FeedType implements java.io.Serializable {

	private Long		id;
	private String		name;
	private String		description;
	private Set<Feed>	feeds	= new HashSet<Feed>(0);

	public FeedType() {
	}

	public FeedType(String name) {
		this.name = name;
	}

	public FeedType(String name, String description, Set<Feed> feeds) {
		this.name = name;
		this.description = description;
		this.feeds = feeds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feedType")
	public Set<Feed> getFeeds() {
		return this.feeds;
	}

	public void setFeeds(Set<Feed> feeds) {
		this.feeds = feeds;
	}

}
