package dendy.rpms.entity;

// Generated 2014-10-26 13:48:43 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HouseTransfer generated by hbm2java
 */
@Entity
@Table(name = "house_transfer", catalog = "rpms")
public class HouseTransfer implements java.io.Serializable {

	private Long	id;
	private House	houseBySrcHouse;
	private Animal	animal;
	private User	userByUpdateUser;
	private User	userByCreateUser;
	private House	houseByDestHouse;
	private String	zoo;
	private Byte	transTarget;
	private Integer	transType;
	private Date	transTime;
	private Date	createTime;
	private Date	updateTime;
	private String	remark;

	public HouseTransfer() {
	}

	public HouseTransfer(House houseBySrcHouse, Animal animal, User userByUpdateUser, User userByCreateUser, House houseByDestHouse,
			String zoo, Byte transTarget, Integer transType, Date transTime, Date createTime, Date updateTime, String remark) {
		this.houseBySrcHouse = houseBySrcHouse;
		this.animal = animal;
		this.userByUpdateUser = userByUpdateUser;
		this.userByCreateUser = userByCreateUser;
		this.houseByDestHouse = houseByDestHouse;
		this.zoo = zoo;
		this.transTarget = transTarget;
		this.transType = transType;
		this.transTime = transTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SRC_HOUSE")
	public House getHouseBySrcHouse() {
		return this.houseBySrcHouse;
	}

	public void setHouseBySrcHouse(House houseBySrcHouse) {
		this.houseBySrcHouse = houseBySrcHouse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ANIMAL")
	public Animal getAnimal() {
		return this.animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATE_USER")
	public User getUserByUpdateUser() {
		return this.userByUpdateUser;
	}

	public void setUserByUpdateUser(User userByUpdateUser) {
		this.userByUpdateUser = userByUpdateUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_USER")
	public User getUserByCreateUser() {
		return this.userByCreateUser;
	}

	public void setUserByCreateUser(User userByCreateUser) {
		this.userByCreateUser = userByCreateUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEST_HOUSE")
	public House getHouseByDestHouse() {
		return this.houseByDestHouse;
	}

	public void setHouseByDestHouse(House houseByDestHouse) {
		this.houseByDestHouse = houseByDestHouse;
	}

	@Column(name = "ZOO", length = 200)
	public String getZoo() {
		return this.zoo;
	}

	public void setZoo(String zoo) {
		this.zoo = zoo;
	}

	@Column(name = "TRANS_TARGET")
	public Byte getTransTarget() {
		return this.transTarget;
	}

	public void setTransTarget(Byte transTarget) {
		this.transTarget = transTarget;
	}

	@Column(name = "TRANS_TYPE")
	public Integer getTransType() {
		return this.transType;
	}

	public void setTransType(Integer transType) {
		this.transType = transType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANS_TIME", length = 19)
	public Date getTransTime() {
		return this.transTime;
	}

	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "REMARK", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
