package dendy.rpms.entity;

// Generated 2014-10-26 13:48:43 by Hibernate Tools 3.6.0

import org.codehaus.jackson.annotate.JsonIgnore;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Primer generated by hbm2java
 */
@Entity
@Table(name = "primer", catalog = "rpms")
public class Primer implements java.io.Serializable {

	private Long				id;
	private User				userByUpdateUser;
	private User				userByCreateUser;
	private String				no;
	private Date				createTime;
	private Date				updateTime;
	private String				remark;
	private Set<AnimalGenotype>	animalGenotypes	= new HashSet<AnimalGenotype>(0);
	private Set<Genotype>		genotypes		= new HashSet<Genotype>(0);

	public Primer() {
	}

	public Primer(String no) {
		this.no = no;
	}

	public Primer(User userByUpdateUser, User userByCreateUser, String no, Date createTime, Date updateTime, String remark,
			Set<AnimalGenotype> animalGenotypes, Set<Genotype> genotypes) {
		this.userByUpdateUser = userByUpdateUser;
		this.userByCreateUser = userByCreateUser;
		this.no = no;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
		this.animalGenotypes = animalGenotypes;
		this.genotypes = genotypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATE_USER")
    @JsonIgnore
	public User getUserByUpdateUser() {
		return this.userByUpdateUser;
	}

	public void setUserByUpdateUser(User userByUpdateUser) {
		this.userByUpdateUser = userByUpdateUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_USER")
    @JsonIgnore
	public User getUserByCreateUser() {
		return this.userByCreateUser;
	}

	public void setUserByCreateUser(User userByCreateUser) {
		this.userByCreateUser = userByCreateUser;
	}

	@Column(name = "NO", nullable = false, length = 100)
	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "REMARK", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "primer")
    @JsonIgnore
	public Set<AnimalGenotype> getAnimalGenotypes() {
		return this.animalGenotypes;
	}

	public void setAnimalGenotypes(Set<AnimalGenotype> animalGenotypes) {
		this.animalGenotypes = animalGenotypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "primer")
    @JsonIgnore
	public Set<Genotype> getGenotypes() {
		return this.genotypes;
	}

	public void setGenotypes(Set<Genotype> genotypes) {
		this.genotypes = genotypes;
	}

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Primer primer = (Primer) o;

        if (id != null ? !id.equals(primer.id) : primer.id != null) return false;
        if (no != null ? !no.equals(primer.no) : primer.no != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (no != null ? no.hashCode() : 0);
        return result;
    }
}
